# vich_uploader:
#     db_driver: orm

#     #mappings:
#     #    products:
#     #        uri_prefix: /images/products
#     #        upload_destination: '%kernel.project_dir%/public/images/products'
#     #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer




vich_uploader:
    db_driver: orm
    
    mappings:
        ressource_files:
            uri_prefix: /uploads/ressources
            upload_destination: '%kernel.project_dir%/public/uploads/ressources'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        rendu_files:
            uri_prefix: /uploads/rendus
            upload_destination: '%kernel.project_dir%/public/uploads/rendus'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer